#!/bin/sh

echo "[rc3.d] sf-svc RC3 script"
	
if [ -x /usr/bin/sf_server ]; then
	/usr/bin/sf_server -s /usr/etc/sf_sensor.conf -f /usr/etc/sf_filter.conf -p /usr/etc/sf_processor.conf -d /usr/etc/sf_data_stream.conf & 
fi

if [ -f /opt/etc/.hib_capturing ]; then
#add waitting for widget-screen, request from booting-TF (for Normal Boot) )
	echo "Fast boot"
	else
	echo "waitting for widget-screen about 17s"
fi

